db:
  image: "postgres:9.3"
  #volumes:
    #- db/postgresql/data/:/var/lib/postgresql/data/
  expose:
    - 5432
web:
  build: .
  command: bundle exec rails server -b '0.0.0.0'
  volumes:
    - .:/cfp
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    RAILS_ENV: 'development'