defaults: &defaults
  mailers:
    from: "cfp@eurucamp.org"
    notifications:
      new_paper: "cfp-new-papers@eurucamp.org"
  errors:
    from: "exception@eurucamp.org"
    to:
      - "cfp-errors@eurucamp.org"
  conference:
    coc_link:
      "https://rubyberlin.github.io/code-of-conduct"
    time_slots:
      - 15 minutes
      - 30 minutes
      - 40 minutes
  conferences:
    - eurucamp
    - jrubyconf
    - euruko

development:
  <<: *defaults

test:
  <<: *defaults
  mailers:
    from: 'test@eurucamp.org'
    notifications:
      new_paper: "somebody@somewhere.com"

staging:
  <<: *defaults
  mailers:
    from: "cfp+staging@eurucamp.org"
    notifications:
      new_paper: "piotr@gega.io"

production:
  <<: *defaults
