defaults: &defaults
  mailers:
    from: "cfp@rustfest.eu"
    notifications:
      new_paper: "cfp-new-papers@rustfest.eu"
  errors:
    from: "exception@rustfest.eu"
    to:
      - "cfp-errors@rustfest.eu"
  conference:
    coc_link:
      "http://rustfest.eu/code-of-conduct/"
    time_slots:
      - 15 minutes
      - 30 minutes
      - 40 minutes
  conferences:
    - rustfest

development:
  <<: *defaults

test:
  <<: *defaults
  mailers:
    from: 'test@rustfest.eu'
    notifications:
      new_paper: "somebody@somewhere.com"

staging:
  <<: *defaults
  mailers:
    from: "cfp+staging@eurucamp.org"
    notifications:
      new_paper: "flo@andersground.net"

production:
  <<: *defaults
