production: 
  stack: cedar
  app:   eurucamp-cfp
  config:
    BUNDLE_WITHOUT: "development:test"

staging:
  stack: cedar
  app:   eurucamp-cfp-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
