production: 
  stack: cedar
  app:   eurucamp-cfp
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-22009575-1"

staging:
  stack: cedar
  app:   eurucamp-cfp-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
